format = """
[](#DD4814)\
$username\
[](bg:#F10E50 fg:#DD4814)\
$memory_usage\
[](bg:#432a61 fg:#F10E50)\
$directory\
[](fg:#432a61 bg:#4f2d32)\
$git_branch\
[](fg:#4f2d32 bg:#8c0000)\
$nodejs\
[](fg:#8c0000 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#1a384a)\
$time\
[ ](fg:#1a384a)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#dd4814 fg:#ffffff"
style_root = "bg:#dd4814 fg:#ffffff"
format = '[ $user]($style)'
disabled = false


[memory_usage]
disabled = false
threshold = -1
symbol = ''
format = '[ $symbol ($ram_pct) ]($style)'
style = 'bg:#F10E50 fg:#ffffff'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = '($style)'
style = "bg:#dd4814"
disabled = false 

[directory]
style = "bg:#432a61"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = " "
style = "bg:#4f2d32"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4f2d32"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#8c0000"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1a384a"
format = '[ $time ]($style)'
